In [1]:
import numpy as np

In [2]:
#Numpy sirve para hacer operaciones de matrices y para crear rangos entre graficas


In [7]:
lista = [1,2,3,4,5,6,7]
arreglo = np.array(lista)
arreglo
type(lista)

list

In [6]:
type(arreglo) #Con el array de numpy puedes saber el numero de dimensiones y el tipo

numpy.ndarray

In [9]:
#Caracteristicas basicas
print('Contenido del arreglo: ',arreglo)
print('Tamaño del arreglo: ',arreglo.size)##tamaño del arreglo
print('Dimensióndel arreglo (dimensiones, numero de elementos)',arreglo.shape)#forma del arreglo
print('Dimensiones del arreglo: ',arreglo.ndim)##numero de dimensiones
print('Tipo de dato del arreglo: ', arreglo.dtype) ##tipo de dato del arreglo, puede ser int, complex, float, etc
print('\n')
# ¿Qué significa 'int64'?  Es la capacidad de almacenamiento ->Int16: 2 bytes; Int32 y int: 4 bytes->Int64 : 8 bytes

# arreglo complejo
arreglo_complejo=np.array([1+3j,5,8+7j], dtype= complex)
print('Contenido del arreglo de tipo complejo', arreglo_complejo)
print('Tipo de dato del arreglo complejo: ', arreglo_complejo.dtype)
print('\n')
# arreglo flotante
arreglo_flotante=np.array([1.9,5,8], dtype= float)
print('Contenido del arreglo de tipo complejo', arreglo_flotante)
print('Tipo de dato del arreglo complejo: ', arreglo_flotante.dtype)

Contenido del arreglo:  [1 2 3 4 5 6 7]
Tamaño del arreglo:  7
Dimensióndel arreglo (dimensiones, numero de elementos) (7,)
Dimensiones del arreglo:  1
Tipo de dato del arreglo:  int64


Contenido del arreglo de tipo complejo [1.+3.j 5.+0.j 8.+7.j]
Tipo de dato del arreglo complejo:  complex128


Contenido del arreglo de tipo complejo [1.9 5.  8. ]
Tipo de dato del arreglo complejo:  float64


In [11]:
arr_bidimensional = np.array([[1,2,3],[1,2,3]])
arr_bidimensional

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
matrix3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ma_zeros = np.zeros((3,3))
ma_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
ma_unos = np.ones((3,3))
ma_unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ma_nueva = ma_zeros + ma_unos + matrix3
ma_nueva

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [21]:
ma_nueva2 = ma_zeros * ma_unos * matrix3
ma_nueva2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
ma_nueva.transpose()

array([[ 2.,  5.,  8.],
       [ 3.,  6.,  9.],
       [ 4.,  7., 10.]])

In [23]:
ma_nueva.diagonal()

array([ 2.,  6., 10.])